// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAugLaNdCUicDBY1Aj-88ky30wLgM3skm8',
    appId: '1:178408403179:web:46905253c5f6d548adceae',
    messagingSenderId: '178408403179',
    projectId: 'chat-app-flutter-10749',
    authDomain: 'chat-app-flutter-10749.firebaseapp.com',
    storageBucket: 'chat-app-flutter-10749.appspot.com',
    measurementId: 'G-9SSF545YFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEe2Z2pZi1dEVLXPx29HIMDf-ePqKRX9s',
    appId: '1:178408403179:android:2126ccb85cced4d1adceae',
    messagingSenderId: '178408403179',
    projectId: 'chat-app-flutter-10749',
    storageBucket: 'chat-app-flutter-10749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ6Ez8iE4X8PYWNm6_z2hQqEKCPyqSWnk',
    appId: '1:178408403179:ios:f5fd3847d62506c5adceae',
    messagingSenderId: '178408403179',
    projectId: 'chat-app-flutter-10749',
    storageBucket: 'chat-app-flutter-10749.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ6Ez8iE4X8PYWNm6_z2hQqEKCPyqSWnk',
    appId: '1:178408403179:ios:f5fd3847d62506c5adceae',
    messagingSenderId: '178408403179',
    projectId: 'chat-app-flutter-10749',
    storageBucket: 'chat-app-flutter-10749.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAugLaNdCUicDBY1Aj-88ky30wLgM3skm8',
    appId: '1:178408403179:web:8fa66272ec0a4e36adceae',
    messagingSenderId: '178408403179',
    projectId: 'chat-app-flutter-10749',
    authDomain: 'chat-app-flutter-10749.firebaseapp.com',
    storageBucket: 'chat-app-flutter-10749.appspot.com',
    measurementId: 'G-JSZKGGRW9Q',
  );
}
